# Generated by Django 3.2.5 on 2021-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
