# Generated by Django 3.2.5 on 2021-07-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profiles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.country'),
        ),
    ]
