# Generated by Django 3.2.5 on 2021-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
