# Generated by Django 3.2.6 on 2021-08-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_focuspoints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FocusPoints',
            new_name='focus_points',
        ),
    ]
