# Generated by Django 3.2.9 on 2021-12-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_focuspoints_focus_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
