# Generated by Django 3.2.5 on 2021-12-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_contact_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='sub_domain',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
