# Generated by Django 3.2.5 on 2021-07-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descreption', models.CharField(blank=True, max_length=30, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='upload/projects_icons/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_projects', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_urls', to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='bullet_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_text', models.TextField(blank=True, max_length=100, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bullet_points', to='projects.projects')),
            ],
        ),
    ]
