# Generated by Django 3.2.6 on 2021-08-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
        ('education', '0003_courses_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='education_id',
        ),
        migrations.AddField(
            model_name='courses',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_courses', to='work_experience.organizations'),
        ),
    ]
