# Generated by Django 3.2.6 on 2021-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_education_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
