# Generated by Django 3.2.5 on 2021-07-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_educations', to='work_experience.organizations')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_education', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('course_expected_time', models.CharField(blank=True, max_length=30, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(blank=True, default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='upload/files/course_certificate')),
                ('education_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_courses', to='education.education')),
            ],
        ),
    ]
