# Generated by Django 3.2.6 on 2021-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('course_expected_time', models.CharField(blank=True, max_length=30, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(blank=True, default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='upload/files/course_certificate')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
