# Generated by Django 3.2.6 on 2021-08-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('profiles', '0001_initial'),
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_educations', to='work_experience.organizations'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_education', to='profiles.profiles'),
        ),
        migrations.AddField(
            model_name='courses',
            name='education_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_courses', to='education.education'),
        ),
    ]
