# Generated by Django 3.2.6 on 2021-08-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20210819_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
