# Generated by Django 3.2.5 on 2021-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.IntegerField(default=None),
        ),
    ]
