# Generated by Django 3.2.5 on 2021-07-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_auto_20210720_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlinks',
            name='award_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award_hyperlinks', to='achievement.award'),
        ),
    ]
