# Generated by Django 3.2.6 on 2021-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
