# Generated by Django 3.2.6 on 2021-08-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_skills',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
