# Generated by Django 3.2.5 on 2021-07-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_skills',
            name='category_i',
        ),
        migrations.AddField(
            model_name='user_skills',
            name='category_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='skills.categories'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.categories'),
        ),
    ]
