# Generated by Django 3.2.5 on 2021-07-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
                ('organization_id', models.ManyToManyField(to='work_experience.organizations')),
            ],
        ),
    ]
