# Generated by Django 3.2.5 on 2021-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0002_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='icon_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='organization_id',
            field=models.ManyToManyField(related_name='organization_tags', to='work_experience.organizations'),
        ),
    ]
