# Generated by Django 3.2.5 on 2021-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0003_auto_20210720_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='icon_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
